# Generated by Django 4.1.5 on 2023-01-31 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='annimal_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('localisation', models.CharField(choices=[(1, 'Alsace'), (2, 'Aquitaine'), (3, 'Auvergne'), (4, 'Basse-Normandie'), (5, 'Bourgogne'), (6, 'Bretagne'), (7, 'Centre'), (8, 'Champagne-Ardennes'), (9, 'Corse'), (10, 'Franche-Comté'), (11, 'Haute-Normandie'), (12, 'Ile-de-France'), (13, 'Languedoc-Roussillon'), (14, 'Limousin'), (15, 'Lorraine'), (16, 'Midi-Pyrénées'), (17, 'Nord-Pas-de-Calais'), (18, 'Pays de la loire'), (19, 'Picardie'), (20, 'Poitou-Charentes'), (21, "Provence-Alpes-Cotes d'Azur"), (22, 'Rhône-Alpes')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=None)),
                ('sexe', models.CharField(choices=[(1, 'mâle'), (2, 'femelle')], max_length=100)),
                ('race', models.CharField(choices=[(1, 'Abyssin'), (2, 'Bengal'), (3, 'Bleu Russe'), (4, 'Bombay'), (5, 'British Shorthair'), (6, 'Chartreux'), (7, 'Maine Coon'), (8, 'Persan'), (9, 'Ragdoll'), (10, 'Sacré de Birmanie'), (11, 'Savannah'), (12, 'Scottish Fold'), (13, 'Siamois'), (14, 'Sibérien'), (15, 'Sphynx'), (16, 'Toyger')], max_length=100)),
                ('bloodtype', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'AB')], max_length=10)),
                ('viral_disease_tests', models.CharField(max_length=1000)),
                ('identification', models.CharField(max_length=15)),
                ('eye_color', models.CharField(choices=[(1, 'Bleus'), (2, 'Verts'), (3, 'Or'), (4, 'Vairons')], max_length=100)),
                ('age', models.CharField(choices=[(1, '6 mois - 1 an'), (2, '1 an - 2 ans'), (3, '2 ans - 3 ans'), (4, '3 ans - 4 ans'), (5, '4 ans - 5 ans'), (6, '5 ans - 6 ans'), (7, '6 ans - 7 ans'), (8, '7 ans - 8 ans'), (9, '8 ans - 9 ans')], max_length=10)),
                ('fur_color', models.CharField(max_length=100)),
                ('qualities_flaws', models.CharField(max_length=350)),
                ('free_descriptive_text', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
