# Generated by Django 4.1.5 on 2023-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annimal_post',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
