# Generated by Django 4.1.5 on 2023-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0002_alter_annimal_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annimal_post',
            name='age',
            field=models.CharField(choices=[('1', '6 mois - 1 an'), ('2', '1 an - 2 ans'), ('3', '2 ans - 3 ans'), ('4', '3 ans - 4 ans'), ('5', '4 ans - 5 ans'), ('6', '5 ans - 6 ans'), ('7', '6 ans - 7 ans'), ('8', '7 ans - 8 ans'), ('9', '8 ans - 9 ans')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='bloodtype',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'AB')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='eye_color',
            field=models.CharField(choices=[('1', 'Bleus'), ('2', 'Verts'), ('3', 'Or'), ('àç4', 'Vairons')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='free_descriptive_text',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='fur_color',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='localisation',
            field=models.CharField(choices=[('1', 'Alsace'), ('2', 'Aquitaine'), ('3', 'Auvergne'), ('4', 'Basse-Normandie'), ('5', 'Bourgogne'), ('6', 'Bretagne'), ('7', 'Centre'), ('8', 'Champagne-Ardennes'), ('9', 'Corse'), ('10', 'Franche-Comté'), ('11', 'Haute-Normandie'), ('12', 'Ile-de-France'), ('13', 'Languedoc-Roussillon'), ('14', 'Limousin'), ('15', 'Lorraine'), ('16', 'Midi-Pyrénées'), ('17', 'Nord-Pas-de-Calais'), ('18', 'Pays de la loire'), ('19', 'Picardie'), ('20', 'Poitou-Charentes'), ('21', "Provence-Alpes-Cotes d'Azur"), ('22', 'Rhône-Alpes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='qualities_flaws',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='race',
            field=models.CharField(choices=[('1', 'Abyssin'), ('2', 'Bengal'), ('3', 'Bleu Russe'), ('4', 'Bombay'), ('5', 'British Shorthair'), ('6', 'Chartreux'), ('7', 'Maine Coon'), ('8', 'Persan'), ('9', 'Ragdoll'), ('10', 'Sacré de Birmanie'), ('11', 'Savannah'), ('12', 'Scottish Fold'), ('13', 'Siamois'), ('14', 'Sibérien'), ('15', 'Sphynx'), ('16', 'Toyger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='sexe',
            field=models.CharField(choices=[('1', 'mâle'), ('2', 'femelle')], max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='viral_disease_tests',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
