# Generated by Django 4.1.5 on 2023-02-15 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0004_alter_annimal_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annimal_post',
            name='age',
            field=models.CharField(blank=True, choices=[('1', '6 mois - 1 an'), ('2', '1 an - 2 ans'), ('3', '2 ans - 3 ans'), ('4', '3 ans - 4 ans'), ('5', '4 ans - 5 ans'), ('6', '5 ans - 6 ans'), ('7', '6 ans - 7 ans'), ('8', '7 ans - 8 ans'), ('9', '8 ans - 9 ans')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='bloodtype',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('1', 'Bleus'), ('2', 'Verts'), ('3', 'Or'), ('àç4', 'Vairons')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='free_descriptive_text',
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='fur_color',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='identification',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15)]),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='qualities_flaws',
            field=models.CharField(blank=True, default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='viral_disease_tests',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
