# Generated by Django 4.1.5 on 2023-02-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0005_alter_annimal_post_age_alter_annimal_post_bloodtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annimal_post',
            name='qualities_flaws',
        ),
        migrations.AddField(
            model_name='annimal_post',
            name='flaws',
            field=models.TextField(blank=True, default=None, max_length=350),
        ),
        migrations.AddField(
            model_name='annimal_post',
            name='qualities',
            field=models.TextField(blank=True, default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='free_descriptive_text',
            field=models.TextField(blank=True, default=None, max_length=2000),
        ),
    ]
