# Generated by Django 4.1.5 on 2023-02-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0007_alter_annimal_post_bloodtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annimal_post',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='annimal_post',
            name='qualities',
        ),
    ]
