# Generated by Django 4.1.5 on 2023-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0009_annimal_post_flaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='annimal_post',
            name='qualities',
            field=models.TextField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='flaws',
            field=models.TextField(blank=True, default=None, max_length=350, null=True),
        ),
    ]
