# Generated by Django 4.1.5 on 2023-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0012_remove_annimal_post_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='annimal_post',
            name='flaws',
            field=models.TextField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='annimal_post',
            name='qualities',
            field=models.TextField(blank=True, default=None, max_length=350, null=True),
        ),
    ]
