# Generated by Django 4.1.5 on 2023-02-22 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0017_annimal_post_flaws_annimal_post_qualities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annimal_post',
            name='bloodtype',
            field=models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'AB'), ('4', '')], default=None, max_length=10, verbose_name='Groupe sanguin'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('1', 'Bleus'), ('2', 'Verts'), ('3', 'Or'), ('4', 'Vairons')], default=None, max_length=100, verbose_name='Couleur des yeux'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='flaws',
            field=models.TextField(blank=True, default=None, max_length=350, null=True, verbose_name='Défauts'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='free_descriptive_text',
            field=models.TextField(blank=True, default=None, max_length=2000, verbose_name='Autre'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='fur_color',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Couleur du poil'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='identification',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name="N° d'identification"),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Prix de la saillie:'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='qualities',
            field=models.TextField(blank=True, default=None, max_length=350, null=True, verbose_name='Qualités'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='sexe',
            field=models.CharField(choices=[('1', 'mâle'), ('2', 'femelle')], max_length=100, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='viral_disease_tests',
            field=models.CharField(blank=True, default=None, max_length=1000, verbose_name='Tests maladies'),
        ),
    ]
