# Generated by Django 4.1.7 on 2023-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breed', '0018_alter_annimal_post_bloodtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annimal_post',
            name='age',
            field=models.CharField(choices=[('1', '6 mois - 1 an'), ('2', '1 an - 2 ans'), ('3', '2 ans - 3 ans'), ('4', '3 ans - 4 ans'), ('5', '4 ans - 5 ans'), ('6', '5 ans - 6 ans'), ('7', '6 ans - 7 ans'), ('8', '7 ans - 8 ans'), ('9', '8 ans - 9 ans')], max_length=10),
        ),
        migrations.AlterField(
            model_name='annimal_post',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('1', 'Bleus'), ('2', 'Verts'), ('3', 'Or'), ('4', 'Vairons'), ('5', '')], default=None, max_length=100, verbose_name='Couleur des yeux'),
        ),
    ]
